### ISSUE TITLE
Possible Stack Overflow?

### ISSUE THREAD

**Issue by scott-steadman** [wiseleyb/koyo-postgres-replication#1]
https://github.com/wiseleyb/koyo-postgres-replication/blob/fc67c7f6fc76767a02241f799307cd4780e35ee7/lib/koyo/repl/postgres_server.rb#L55

Won't calling ``run!`` within the ``run!`` method eventually cause a stack overflow?
Or does ruby handle tail recursion by default now?

**Comment by wiseleyb** [comment]
I don't think so. I had something pretty similar to this running for years and that never happened. The only real issue was if someone did some massive SQL update reading from the slot would time out. While this is rewrite of the code I originally did this simple logic is the same. 

I guess I could convert to a loop - that might be better.

Thanks for the feedback.

**Comment by wiseleyb** [comment]
Yeah - calling `run` is dumb. Will convert to use a loop tomorrow. Thanks again!

**Comment by scott-steadman** [comment]
You're welcome!

**Comment by wiseleyb** [comment]
Fixed in 0.1.1.pre ... thanks again
